version: '2'
services:
  app:
    image: "node:14-slim"
    container_name: fairy-server
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - VERSION=1.0
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
    ports:
      - "3310:3000"
    tty: true
    command: npm run start:dev
    extra_hosts:
      - "master:host-gateway"
    #command: "npm start"
    #command: "tail -f /dev/null"